[package]
name = "lidar-native"
version = "0.1.0"
authors = ["WUXIANGCHAO cfd.xiangchao.wu@gmial.com"]
edition = "2024"

[dependencies]
# 窗口和事件
winit = "0.29"

# 3D 渲染
wgpu = "0.19"
bytemuck = { version = "1.12", features = ["derive"] }

# 2D UI 界面
egui = "0.27"
egui-wgpu = "0.27"
egui-winit = "0.27"
egui_extras = "0.27"

# 异步运行时 (用于初始化)
tokio = { version = "1", features = ["full"] }

# 数据处理与数学
anyhow = "1.0"
calamine = "0.23"
glam = { version = "0.27", features = ["mint", "bytemuck", "serde"] }
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }

# 日志
log = "0.4"
chrono = "0.4"
hex = "0.4"
egui_plot = "0.27"
rfd = "0.14"
image = "0.25.1"

# 点云处理
kdtree = "0.6"

[build-dependencies]
winres = "0.1"